### ISSUE TITLE
could we move repo to TypeStrong?

### ISSUE THREAD

**Issue by gdi2290** [dzharii/awesome-typescript#11]
cc @blakeembrey

**Comment by blakeembrey** [comment]
That could be useful and we can collaborate on keeping it up to date? Any thoughts @dzharii? My biggest concern is that this list could be more complete - for example, let's link to "the" Webpack plugin to use, the System.JS plugin to use, the Gulp plugin to use, the Grunt plugin to use, the Browserify plugin to use. For example, I'm not sure why Grunt plugins are bundled under the Browserify topic - a good link would be https://github.com/smrq/tsify.

**Comment by dzharii** [comment]
@blakeembrey, gdi2290

No guys, 
I am not going to move this repository anywhere. 

On the other hand, please check the licence for this repo: it is "unlicensed" and you can do whatever you want with this content without asking my permission. You can clone this repo and put into TypeStrong and I do not mind about that. 
But, I am not going to support any other typescript repo except this one.
