### ISSUE TITLE
Add SnowFS

### ISSUE THREAD

**Issue by seb-mtl** [dzharii/awesome-typescript#146]
Hi!

Thanks for the great list! Are new projects welcome? I would like to propose a new project called SnowFS, especially since the project is looking for more contributors. https://github.com/Snowtrack/SnowFS

Thank you!

**Comment by dzharii** [comment]
Hi @seb-mtl ! 
Of course such good projects are always welcome. Could you make a pull request?

**Comment by seb-mtl** [comment]
Thanks, that's awesome! I just created the PR
