### ISSUE TITLE
TypeScript Reference

### ISSUE THREAD

**Issue by welldan97** [dzharii/awesome-typescript#178]
Hi! I created TypeScript Reference.It is here https://github.com/welldan97/typescript-reference

I could not find something like an MDN reference for TS - a unified glossary for keywords, operators, and other language features distinct from JavaScript. So I written it myself.

Can I submit a PR for your amazing list, and if so, in which section should we put it?

**Comment by dzharii** [comment]
@welldan97 affirmative! 👍

Please, create a new category (maybe "Reference lists") after "Books"

Thank you!
