### ISSUE TITLE
Update DefinitelyTyped Page Link to Point to Repo Instead

### ISSUE THREAD

**Issue by smontana** [dzharii/awesome-typescript#195]
The page being served for the [DefinitelyTtyped](www.definitelytyped.org) link just says "webseo1" at the top, and it's not being served over an HTTPS connection:

![definitelytyped org_2023-03-03_at_10 13 37 AM](https://user-images.githubusercontent.com/8894479/222771280-25c848b6-5b7c-4b7c-b9f9-5e7b985026a6.png)

It would make more sense to change that link to the repo itself or to the `Admin Manual` that is referenced in the repo.

- Repo Link: `https://github.com/DefinitelyTyped/DefinitelyTyped`
- Admin Manual Link: `https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/docs/admin.md`

**Comment by dzharii** [comment]
thank you @smontana
