### ISSUE TITLE
typical

### ISSUE THREAD

**Issue by ccorcos** [dzharii/awesome-typescript#39]
This belongs on here: https://github.com/tycho01/typical

**Comment by dzharii** [comment]
Hi @ccorcos could you please add more details and some context and expected outcome on this issue?

**Comment by ccorcos** [comment]
Hey, sorry for the lack of context -- I think there should be a section on here for TypeScript utilities and stuff related to "type-level programming". Here's another related project: https://github.com/gcanti/typelevel-ts

So for example, suppose I have a really large object that goes into a database and I want to define the type of another object as the same object but omitting a few keys. These libraries give you built in facilities to do this: `ObjectOmit<LargeRecord, "omittedKey">`.

Typical is still a work in progress but it is a very deep and maybe even turing complete implemention that gives you utilities for things like array lengths as type literals: `const x: Length<[1,2,3]> = 3`. Pretty fascinating stuff if you ask me.

Cheers

**Comment by dzharii** [comment]
@ccorcos I would call a new section "Crazy stuff". Just kidding, yes, please came up with a name for a new section and submit this crazy stuff as a pull request.

**Comment by stereobooster** [comment]
Maybe name this section "Types"?

I would add my link under this section https://github.com/stereobooster/type-o-rama

Maybe this link will go in this section too https://github.com/gcanti/elm-ts

**Comment by dzharii** [comment]
@stereobooster please feel free to add a new section "Types" and the links you'd like to contribute in a new PR !
