### ISSUE TITLE
Can you add my libraries; TSTL & ECOL ?

### ISSUE THREAD

**Issue by samchon** [dzharii/awesome-typescript#51]
- TSTL: https://github.com/samchon/tstl
- ECOL: https://github.com/samchon/ecol

TSTL is an open-source project providing features of STL (Standard Template Library), migrated from C++ to TypeScript. Principle features of STL are almost implemented in the TSTL
  - containers
  - iterators
  - algorithms
  - functors

ECOL is an extension module of such TSTL, providing special collections dispatching events. The special collections are almost similar with the original STL Containers, but you also can observe elements' I/O events with the special collections. Types of the event dispatched by the special collections are "insert", "erase" and "refresh".

**Comment by dzharii** [comment]
@samchon that's a crazy idea. 
Of course I can add it ;) Btw, did you see this project? 
https://github.com/agentframework/agentframework

I am looking forward to review merge Pull Request. I believe TSTL & ECOL deserve a new category in the list, please come up with the name ;)

Great work @samchon, keep going!

**Comment by dzharii** [comment]
https://github.com/dzharii/awesome-typescript/blob/master/contributing.md

**Comment by samchon** [comment]
Thanks for your fast response. I haven't heard about the `agentframework`.
