### ISSUE TITLE
Include contribution guidelines

### ISSUE THREAD

**Issue by arthurvr** [dzharii/awesome-typescript#6]
With clear guidelines when en how to contribute.

Ref https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines

**Comment by dzharii** [comment]
@arthurvr done. please see:
https://github.com/dzharii/awesome-typescript

**Comment by dzharii** [comment]
Attached merged pull request : 
https://github.com/dzharii/awesome-typescript/pull/7
