### ISSUE TITLE
substitute.js is definitely worth a mention

### ISSUE THREAD

**Issue by ffMathy** [dzharii/awesome-typescript#60]
It's a library I ported from NSubstitute now that TypeScript 3.0 is out, and it allows for a very cool syntax when mocking.

https://github.com/ffMathy/FluffySpoon.JavaScript.Testing

**Comment by dzharii** [comment]
@ffMathy I like it! Could you please make a Pull Request?

**Comment by ffMathy** [comment]
PR #61 opened.

**Comment by dzharii** [comment]
PR #61 Merged
